import {
  Exercise,
  WorkoutTemplate,
  Achievement,
  UserStats,
  UserTrainingProfile,
  UserProfile,
} from "./types";
import { Challenge } from "./domain/entities";

export const EXERCISES: Exercise[] = [
  // Peito
  {
    id: "1",
    name: "Supino Reto",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=sqOw2Y6uDWQ",
  },
  {
    id: "16",
    name: "Supino Inclinado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=Z1G_S9v0_o4",
  },
  {
    id: "17",
    name: "Supino Declinado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito inferior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=LfyQbuMZ9pI",
  },
  {
    id: "18",
    name: "Crucifixo Reto",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=eGjt4lk6g34",
  },
  {
    id: "9",
    name: "Flexão de Braços",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
  },

  // Pernas
  {
    id: "2",
    name: "Agachamento Livre",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 4,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=R2dMsNhN3DE",
  },
  {
    id: "7",
    name: "Leg Press",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
  },
  {
    id: "19",
    name: "Cadeira Extensora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=m0FOpMEgero",
  },
  {
    id: "20",
    name: "Mesa Flexora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=1Tq3Qd1nwro",
  },
  {
    id: "21",
    name: "Stiff",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=1uDiW17GV_Y",
  },
  {
    id: "22",
    name: "Elevação Pélvica",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=SEdqcd8j_S8",
  },
  {
    id: "23",
    name: "Cadeira Adutora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Adutor",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=fXv0mY7_9p0",
  },
  {
    id: "24",
    name: "Cadeira Abdutora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Abdutor",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=2vjS6Xv7_u0",
  },
  {
    id: "25",
    name: "Gêmeos em Pé",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=N3_vS_8p6_w",
  },
  {
    id: "10",
    name: "Afundo",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
  },
  {
    id: "12",
    name: "Alongamento de Isquiotibiais",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 2,
    defaultReps: 30,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=mS9v0_o4",
  },

  // Costas
  {
    id: "3",
    name: "Remada Curvada",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=9efgcAjQ870",
  },
  {
    id: "6",
    name: "Levantamento Terra",
    muscleGroup: "Costas",
    muscleSubgroup: "Lombar",
    defaultSets: 3,
    defaultReps: 5,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
  },
  {
    id: "8",
    name: "Puxada Alta",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
  },
  {
    id: "26",
    name: "Encolhimento",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=cJRVVxmytaM",
  },
  {
    id: "27",
    name: "Remada Cavalinho",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=j3S_Xp_8p6_w",
  },
  {
    id: "15",
    name: "Remada com Elástico",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Elástico",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=j3S_Xp_8p6_w",
  },

  // Ombros
  {
    id: "4",
    name: "Desenvolvimento Militar",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=2yjwxtpY_pY",
  },
  {
    id: "28",
    name: "Elevação Lateral",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
  },
  {
    id: "29",
    name: "Crucifixo Inverso",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=6yjwxtpY_pY",
  },

  // Braços
  {
    id: "5",
    name: "Rosca Direta",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },
  {
    id: "13",
    name: "Rosca com Halter",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },
  {
    id: "30",
    name: "Tríceps Pulley",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzHLw",
  },
  {
    id: "31",
    name: "Tríceps Testa",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=jPZ_Xp_8p6_w",
  },
  {
    id: "32",
    name: "Rosca Inversa",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },

  // Core
  {
    id: "11",
    name: "Prancha Abdominal",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 60,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "33",
    name: "Abdominal Supra",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "34",
    name: "Abdominal Infra",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "35",
    name: "Giro Russo",
    muscleGroup: "Core",
    muscleSubgroup: "Oblíquos",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },

  // Full Body
  {
    id: "14",
    name: "Kettlebell Swing",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 20,
    category: "Funcional",
    equipment: "Kettlebell",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },

  // Cardio
  {
    id: "36",
    name: "Corrida",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "37",
    name: "Ciclismo",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 45,
    category: "Funcional",
    equipment: "Máquina",
    type: "cardio",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "38",
    name: "Pular Corda",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 120,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
];

export const calculateChallengeXP = (
  difficulty: "easy" | "medium" | "hard" | "epic",
  durationDays: number,
): number => {
  const baseXP = {
    easy: 50,
    medium: 150,
    hard: 300,
    epic: 500,
  };

  // Multiplier based on duration
  const durationMultiplier =
    durationDays > 7 ? 1.5 : durationDays > 1 ? 1.2 : 1;

  return Math.round(baseXP[difficulty] * durationMultiplier);
};

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "c1",
    title: "Treino Rápido",
    description: "Complete 1 treino hoje.",
    type: "frequency",
    category: "daily",
    difficulty: "easy",
    goal: 1,
    durationDays: 1,
    rewardXp: calculateChallengeXP("easy", 1),
    icon: "Zap",
  },
  {
    id: "c2",
    title: "Maratona de Supino",
    description: "Levante um total de 5000kg no Supino Reto.",
    type: "volume",
    category: "weekly",
    difficulty: "medium",
    goal: 5000,
    durationDays: 7,
    rewardXp: calculateChallengeXP("medium", 7),
    icon: "Dumbbell",
  },
  {
    id: "c3",
    title: "Semana Perfeita",
    description: "Treine 5 dias nesta semana.",
    type: "frequency",
    category: "weekly",
    difficulty: "hard",
    goal: 5,
    durationDays: 7,
    rewardXp: calculateChallengeXP("hard", 7),
    icon: "Calendar",
  },
  {
    id: "c4",
    title: "Desafio da Comunidade: 10k",
    description: "Corra 10km acumulados.",
    type: "volume",
    category: "community",
    difficulty: "epic",
    goal: 10,
    durationDays: 14,
    rewardXp: calculateChallengeXP("epic", 14),
    icon: "Trophy",
    communityId: "mock-community-1",
  },
];

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [];

export const ACHIEVEMENTS: Achievement[] = [
  // Athlete Achievements
  {
    id: "a1",
    name: "Primeiro Treino",
    description: "Complete seu primeiro treino.",
    category: "Consistency",
    criteria: "1 treino",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Dumbbell",
    xpValue: 100,
  },
  {
    id: "a2",
    name: "Streak 7 Dias",
    description: "Treine por 7 dias seguidos.",
    category: "Consistency",
    criteria: "7 dias",
    progress: 3,
    maxProgress: 7,
    icon: "Flame",
    xpValue: 500,
  },
  {
    id: "a3",
    name: "PR no Supino",
    description: "Bata seu recorde pessoal no Supino.",
    category: "Strength",
    criteria: "Novo recorde",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Trophy",
    xpValue: 250,
  },
  {
    id: "a4",
    name: "Volume 100k kg",
    description: "Acumule 100.000 kg de volume total.",
    category: "Volume",
    criteria: "100.000 kg",
    progress: 45000,
    maxProgress: 100000,
    icon: "Weight",
    xpValue: 1000,
  },
  {
    id: "a5",
    name: "Atleta Focado",
    description: "Complete 10 treinos no total.",
    category: "Consistency",
    criteria: "10 treinos",
    progress: 4,
    maxProgress: 10,
    icon: "Target",
    xpValue: 800,
  },
  {
    id: "a6",
    name: "Madrugador",
    description: "Treine 5 vezes antes das 8h da manhã.",
    category: "Frequency",
    criteria: "5 treinos",
    progress: 2,
    maxProgress: 5,
    icon: "Sun",
    xpValue: 600,
  },

  // Trainer Achievements
  {
    id: "t1",
    name: "Primeiro Aluno",
    description: "Conecte-se com seu primeiro aluno.",
    category: "Engagement",
    criteria: "1 aluno",
    progress: 1,
    maxProgress: 1,
    icon: "Users",
    xpValue: 200,
  },
  {
    id: "t2",
    name: "Mestre dos Treinos",
    description: "Crie 10 templates de treino.",
    category: "Mentorship",
    criteria: "10 templates",
    progress: 4,
    maxProgress: 10,
    icon: "FileText",
    xpValue: 500,
  },
  {
    id: "t3",
    name: "Treinador Popular",
    description: "Tenha 10 alunos ativos simultaneamente.",
    category: "Community",
    criteria: "10 alunos",
    progress: 3,
    maxProgress: 10,
    icon: "Star",
    xpValue: 1000,
  },
  {
    id: "t4",
    name: "Feedback Constante",
    description: "Envie 20 mensagens para seus alunos.",
    category: "Engagement",
    criteria: "20 mensagens",
    progress: 12,
    maxProgress: 20,
    icon: "MessageSquare",
    xpValue: 400,
  },
  {
    id: "t5",
    name: "Alunos Focados",
    description: "Seus alunos completaram 50 treinos no total.",
    category: "Mentorship",
    criteria: "50 treinos",
    progress: 23,
    maxProgress: 50,
    icon: "Award",
    xpValue: 1500,
  },
  {
    id: "t6",
    name: "Treinador de Elite",
    description: "5 alunos atingiram streak de 7 dias.",
    category: "Mentorship",
    criteria: "5 alunos",
    progress: 1,
    maxProgress: 5,
    icon: "Crown",
    xpValue: 2000,
  },
  
  // Challenge Achievements
  {
    id: "c1",
    name: "Desafiante Iniciante",
    description: "Complete seu primeiro desafio.",
    category: "Challenges",
    criteria: "1 desafio",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Swords",
    xpValue: 150,
  },
  {
    id: "c2",
    name: "Competidor Nato",
    description: "Complete 10 desafios no total.",
    category: "Challenges",
    criteria: "10 desafios",
    progress: 3,
    maxProgress: 10,
    icon: "Medal",
    xpValue: 600,
  },
  {
    id: "c3",
    name: "Rei do Cardio",
    description: "Complete 5 desafios da categoria Cardio.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 2,
    maxProgress: 5,
    icon: "Activity",
    xpValue: 400,
  },
  {
    id: "c4",
    name: "Força Bruta",
    description: "Complete 5 desafios da categoria Força.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 1,
    maxProgress: 5,
    icon: "Dumbbell",
    xpValue: 400,
  },
  {
    id: "c5",
    name: "Consistência de Ferro",
    description: "Complete 5 desafios da categoria Consistência.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 4,
    maxProgress: 5,
    icon: "Flame",
    xpValue: 400,
  }
];

export const MOCK_PROTOCOLS = [];

export const DEFAULT_STATS: UserStats = {
  level: 1,
  xp: 0,
  streak: 0,
  bestStreak: 0,
  weeklyGoal: 3,
  completedThisWeek: 0,
  totalWorkouts: 0,
  totalVolume: 0,
  medalsCount: 0,
  league: "Bronze",
};

export const DEFAULT_TRAINING_PROFILE: UserTrainingProfile = {
  user_id: "",
  avg_set_duration: 45,
  avg_rest_duration: 90,
  avg_transition_duration: 120,
  avg_workout_duration: 3600,
};

export const DEFAULT_PROFILE: UserProfile = {
  name: "",
  email: "",
  height: 0,
  initialWeight: 0,
  objective: "",
  birthDate: "",
  avatarUrl:
    "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=2070&auto=format&fit=crop",
  userType: "atleta",
};
