import {
  Exercise,
  WorkoutTemplate,
  Achievement,
  UserStats,
  UserTrainingProfile,
  UserProfile,
} from "./domain/entities";
import { Challenge } from "./domain/entities";

export const EXERCISES: Exercise[] = [
  // Peito
  {
    id: "1",
    name: "Supino reto",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=sqOw2Y6uDWQ",
  },
  {
    id: "16",
    name: "Supino inclinado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=Z1G_S9v0_o4",
  },
  {
    id: "17",
    name: "Supino declinado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito inferior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=LfyQbuMZ9pI",
  },
  {
    id: "18",
    name: "Crucifixo reto",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=eGjt4lk6g34",
  },
  {
    id: "9",
    name: "Flexão de braços",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
    inputMode: "reps_only",
    youtubeUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
  },

  // Pernas
  {
    id: "2",
    name: "Agachamento livre",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 4,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=R2dMsNhN3DE",
  },
  {
    id: "7",
    name: "Leg press",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
  },
  {
    id: "19",
    name: "Cadeira extensora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=m0FOpMEgero",
  },
  {
    id: "20",
    name: "Mesa flexora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=1Tq3Qd1nwro",
  },
  {
    id: "21",
    name: "Stiff",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=1uDiW17GV_Y",
  },
  {
    id: "22",
    name: "Elevação pélvica",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=SEdqcd8j_S8",
  },
  {
    id: "23",
    name: "Cadeira adutora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Adutor",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=fXv0mY7_9p0",
  },
  {
    id: "24",
    name: "Cadeira abdutora",
    muscleGroup: "Pernas",
    muscleSubgroup: "Abdutor",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=2vjS6Xv7_u0",
  },
  {
    id: "25",
    name: "Gêmeos em pé",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=N3_vS_8p6_w",
  },
  {
    id: "10",
    name: "Afundo",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
    inputMode: "reps_only",
    youtubeUrl: "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
  },
  {
    id: "12",
    name: "Alongamento de isquiotibiais",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 2,
    defaultReps: 30,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "isolation",
    inputMode: "duration_only",
    youtubeUrl: "https://www.youtube.com/watch?v=mS9v0_o4",
  },

  // Costas
  {
    id: "3",
    name: "Remada curvada",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=9efgcAjQ870",
  },
  {
    id: "6",
    name: "Levantamento terra",
    muscleGroup: "Costas",
    muscleSubgroup: "Lombar",
    defaultSets: 3,
    defaultReps: 5,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
  },
  {
    id: "8",
    name: "Puxada alta",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
  },
  {
    id: "26",
    name: "Encolhimento",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=cJRVVxmytaM",
  },
  {
    id: "27",
    name: "Remada cavalinho",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=j3S_Xp_8p6_w",
  },
  {
    id: "15",
    name: "Remada com elástico",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Elástico",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=j3S_Xp_8p6_w",
  },

  // Ombros
  {
    id: "4",
    name: "Desenvolvimento militar",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=2yjwxtpY_pY",
  },
  {
    id: "28",
    name: "Elevação lateral",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
  },
  {
    id: "29",
    name: "Crucifixo inverso",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=6yjwxtpY_pY",
  },

  // Braços
  {
    id: "5",
    name: "Rosca direta",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },
  {
    id: "13",
    name: "Rosca com halter",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },
  {
    id: "30",
    name: "Tríceps pulley",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzHLw",
  },
  {
    id: "31",
    name: "Tríceps testa",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=jPZ_Xp_8p6_w",
  },
  {
    id: "32",
    name: "Rosca inversa",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0_o",
  },

  // Core
  {
    id: "11",
    name: "Prancha abdominal",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 60,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "33",
    name: "Abdominal supra",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "reps_only",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "34",
    name: "Abdominal infra",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "reps_only",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "35",
    name: "Giro russo",
    muscleGroup: "Core",
    muscleSubgroup: "Oblíquos",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "reps_only",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },

  // Peito — novos
  {
    id: "39",
    name: "Supino reto com halteres",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "40",
    name: "Supino inclinado com halteres",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "41",
    name: "Supino declinado com halteres",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito inferior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "42",
    name: "Crucifixo inclinado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "43",
    name: "Pullover",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "44",
    name: "Chest press",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "45",
    name: "Peck deck",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "46",
    name: "Supino articulado",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "47",
    name: "Crossover alto",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito inferior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "48",
    name: "Crossover médio",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "49",
    name: "Crossover baixo",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "50",
    name: "Flexão inclinada",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito inferior",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
  },
  {
    id: "51",
    name: "Flexão declinada",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito superior",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
  },
  {
    id: "52",
    name: "Flexão arqueiro",
    muscleGroup: "Peito",
    muscleSubgroup: "Peito médio",
    defaultSets: 3,
    defaultReps: 10,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
  },

  // Costas — novos
  {
    id: "53",
    name: "Remada Pendlay",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "54",
    name: "Barra fixa pronada",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra fixa",
    type: "compound",
  },
  {
    id: "55",
    name: "Barra fixa supinada",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra fixa",
    type: "compound",
  },
  {
    id: "56",
    name: "Barra neutra",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra fixa",
    type: "compound",
  },
  {
    id: "57",
    name: "Puxada articulada",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "58",
    name: "Remada máquina",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "59",
    name: "Pulldown",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "60",
    name: "Remada unilateral",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "61",
    name: "Remada serrote",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "62",
    name: "Remada baixa",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Polia",
    type: "compound",
  },
  {
    id: "63",
    name: "Remada sentado",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Polia",
    type: "compound",
  },
  {
    id: "64",
    name: "Pullover na polia",
    muscleGroup: "Costas",
    muscleSubgroup: "Dorsal",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },

  // Ombros — novos
  {
    id: "65",
    name: "Desenvolvimento atrás da nuca",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "66",
    name: "Desenvolvimento sentado",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "67",
    name: "Elevação frontal",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "68",
    name: "Desenvolvimento máquina",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Anterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "69",
    name: "Elevação lateral inclinada",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "70",
    name: "Elevação lateral unilateral",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "71",
    name: "Elevação lateral atrás do corpo",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "72",
    name: "Elevação lateral máquina",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Lateral",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "73",
    name: "Face pull",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Posterior",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "74",
    name: "Peck deck inverso",
    muscleGroup: "Ombros",
    muscleSubgroup: "Deltoide Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },

  // Trapézio — novos
  {
    id: "75",
    name: "Encolhimento com barra",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "76",
    name: "High pull",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "77",
    name: "Encolhimento na polia",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "78",
    name: "Encolhimento máquina",
    muscleGroup: "Costas",
    muscleSubgroup: "Trapézio",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },

  // Bíceps — novos
  {
    id: "79",
    name: "Rosca w",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "80",
    name: "Rosca drag",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "81",
    name: "Rosca alternada",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "82",
    name: "Rosca concentrada",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "83",
    name: "Rosca martelo",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "84",
    name: "Rosca inclinada",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "85",
    name: "Rosca na polia baixa",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "86",
    name: "Rosca unilateral",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "87",
    name: "Rosca Scott máquina",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "88",
    name: "Rosca Scott barra",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Banco Scott",
    type: "isolation",
  },
  {
    id: "89",
    name: "Rosca Scott halter",
    muscleGroup: "Braços",
    muscleSubgroup: "Bíceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Banco Scott",
    type: "isolation",
  },

  // Tríceps — novos
  {
    id: "90",
    name: "Tríceps francês",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "91",
    name: "Francês unilateral",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "92",
    name: "Coice",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "isolation",
  },
  {
    id: "93",
    name: "Tríceps corda",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "94",
    name: "Tríceps barra reta",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "95",
    name: "Tríceps inverso",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "96",
    name: "Extensão acima da cabeça",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "97",
    name: "Tríceps máquina",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "98",
    name: "Paralelas",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
  },
  {
    id: "99",
    name: "Mergulho no banco",
    muscleGroup: "Braços",
    muscleSubgroup: "Tríceps",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "compound",
  },

  // Antebraço — novos
  {
    id: "100",
    name: "Rosca punho",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "101",
    name: "Rosca punho inversa",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },
  {
    id: "102",
    name: "Farmer walk",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "103",
    name: "Dead hang",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Barra fixa",
    type: "isolation",
  },
  {
    id: "104",
    name: "Extensão de punho",
    muscleGroup: "Braços",
    muscleSubgroup: "Antebraço",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Barra",
    type: "isolation",
  },

  // Abdômen — novos
  {
    id: "105",
    name: "Crunch",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 20,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
  },
  {
    id: "106",
    name: "Abdominal máquina",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "core",
  },
  {
    id: "107",
    name: "Elevação de pernas",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
  },
  {
    id: "108",
    name: "Elevação de joelhos",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "core",
  },
  {
    id: "109",
    name: "Woodchopper",
    muscleGroup: "Core",
    muscleSubgroup: "Oblíquos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Funcional",
    equipment: "Polia",
    type: "core",
  },
  {
    id: "110",
    name: "Prancha lateral",
    muscleGroup: "Core",
    muscleSubgroup: "Oblíquos",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
  },
  {
    id: "111",
    name: "Dead bug",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 10,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
  },
  {
    id: "112",
    name: "Hollow hold",
    muscleGroup: "Core",
    muscleSubgroup: "Abdominais",
    defaultSets: 3,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "core",
  },

  // Quadríceps — novos
  {
    id: "113",
    name: "Front squat",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 4,
    defaultReps: 8,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "114",
    name: "Hack machine",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "compound",
  },
  {
    id: "115",
    name: "Agachamento Goblet",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "116",
    name: "Passada",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "117",
    name: "Avanço",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "118",
    name: "Agachamento Smith",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 4,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Smith",
    type: "compound",
  },
  {
    id: "119",
    name: "Búlgaro Smith",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Smith",
    type: "compound",
  },

  // Posterior de coxa — novos
  {
    id: "120",
    name: "Levantamento terra Romeno",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "121",
    name: "Good morning",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "122",
    name: "Flexora sentada",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "123",
    name: "Stiff com halteres",
    muscleGroup: "Pernas",
    muscleSubgroup: "Posterior",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },

  // Glúteos — novos
  {
    id: "124",
    name: "Hip thrust",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "125",
    name: "Agachamento sumô",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Barra",
    type: "compound",
  },
  {
    id: "126",
    name: "Glúteo máquina",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "127",
    name: "Abdução máquina",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "128",
    name: "Coice na polia",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "129",
    name: "Abdução na polia",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "130",
    name: "Afundo Búlgaro",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 10,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },
  {
    id: "131",
    name: "Step-up",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Halter",
    type: "compound",
  },

  // Adutores — novos
  {
    id: "132",
    name: "Passada lateral",
    muscleGroup: "Pernas",
    muscleSubgroup: "Adutor",
    defaultSets: 3,
    defaultReps: 12,
    category: "Musculação",
    equipment: "Peso corporal",
    type: "compound",
  },

  // Abdutores — novos
  {
    id: "133",
    name: "Abdução unilateral",
    muscleGroup: "Pernas",
    muscleSubgroup: "Abdutor",
    defaultSets: 3,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Polia",
    type: "isolation",
  },
  {
    id: "134",
    name: "Caminhada lateral",
    muscleGroup: "Pernas",
    muscleSubgroup: "Abdutor",
    defaultSets: 3,
    defaultReps: 20,
    category: "Funcional",
    equipment: "Elástico",
    type: "isolation",
  },
  {
    id: "135",
    name: "Monster walk",
    muscleGroup: "Pernas",
    muscleSubgroup: "Abdutor",
    defaultSets: 3,
    defaultReps: 20,
    category: "Funcional",
    equipment: "Elástico",
    type: "isolation",
  },

  // Panturrilhas — novos
  {
    id: "136",
    name: "Panturrilha em pé máquina",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "137",
    name: "Panturrilha Smith",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Smith",
    type: "isolation",
  },
  {
    id: "138",
    name: "Panturrilha sentada",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "139",
    name: "Panturrilha no leg press",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 4,
    defaultReps: 15,
    category: "Musculação",
    equipment: "Máquina",
    type: "isolation",
  },
  {
    id: "140",
    name: "Elevação unilateral",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 3,
    defaultReps: 15,
    category: "Exercício em casa",
    equipment: "Peso corporal",
    type: "isolation",
  },
  {
    id: "141",
    name: "Saltos pliométricos",
    muscleGroup: "Pernas",
    muscleSubgroup: "Panturrilha",
    defaultSets: 3,
    defaultReps: 10,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "compound",
  },

  // Full Body
  {
    id: "14",
    name: "Kettlebell swing",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 20,
    category: "Funcional",
    equipment: "Kettlebell",
    type: "compound",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },

  // Cardio
  {
    id: "36",
    name: "Corrida",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 30,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "37",
    name: "Ciclismo",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 45,
    category: "Funcional",
    equipment: "Máquina",
    type: "cardio",
    inputMode: "duration_distance",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },
  {
    id: "39",
    name: "Natação",
    muscleGroup: "Full Body",
    defaultSets: 1,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },
  {
    id: "38",
    name: "Pular corda",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 120,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_only",
    youtubeUrl: "https://www.youtube.com/watch?v=pvIjsGZ0Zmc",
  },

  // Corrida / Caminhada
  {
    id: "40",
    name: "Caminhada",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },
  {
    id: "41",
    name: "Trote",
    muscleGroup: "Pernas",
    defaultSets: 1,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },

  // Natação — estilos
  {
    id: "42",
    name: "Nado crawl",
    muscleGroup: "Full Body",
    defaultSets: 4,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },
  {
    id: "43",
    name: "Nado costas",
    muscleGroup: "Costas",
    defaultSets: 3,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },
  {
    id: "44",
    name: "Nado peito",
    muscleGroup: "Peito",
    defaultSets: 3,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },
  {
    id: "45",
    name: "Nado borboleta",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 1,
    category: "Funcional",
    equipment: "Peso corporal",
    type: "cardio",
    inputMode: "duration_distance",
  },

  // Yoga / Alongamento
  {
    id: "142",
    name: "Postura da criança (Balasana)",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 1,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
  },
  {
    id: "143",
    name: "Cachorro olhando para baixo (Adho Mukha)",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 1,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
  },
  {
    id: "144",
    name: "Guerreiro I (Virabhadrasana)",
    muscleGroup: "Pernas",
    muscleSubgroup: "Quadríceps",
    defaultSets: 3,
    defaultReps: 1,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
  },
  {
    id: "145",
    name: "Postura da árvore (Vrksasana)",
    muscleGroup: "Full Body",
    defaultSets: 3,
    defaultReps: 1,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
  },
  {
    id: "146",
    name: "Alongamento de quadril (Pombo)",
    muscleGroup: "Pernas",
    muscleSubgroup: "Glúteos",
    defaultSets: 2,
    defaultReps: 1,
    category: "Alongamento",
    equipment: "Peso corporal",
    type: "core",
    inputMode: "duration_only",
  },
];

export const calculateChallengeXP = (
  difficulty: "easy" | "medium" | "hard" | "epic",
  durationDays: number,
): number => {
  const baseXP = {
    easy: 50,
    medium: 150,
    hard: 300,
    epic: 500,
  };

  // Multiplier based on duration
  const durationMultiplier =
    durationDays > 7 ? 1.5 : durationDays > 1 ? 1.2 : 1;

  return Math.round(baseXP[difficulty] * durationMultiplier);
};

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "c1",
    title: "Treino Rápido",
    description: "Complete 1 treino hoje.",
    type: "frequency",
    category: "daily",
    difficulty: "easy",
    goal: 1,
    durationDays: 1,
    rewardXp: calculateChallengeXP("easy", 1),
    icon: "Zap",
  },
  {
    id: "c2",
    title: "Maratona de Supino",
    description: "Levante um total de 5000kg no Supino Reto.",
    type: "volume",
    category: "weekly",
    difficulty: "medium",
    goal: 5000,
    durationDays: 7,
    rewardXp: calculateChallengeXP("medium", 7),
    icon: "Dumbbell",
  },
  {
    id: "c3",
    title: "Semana Perfeita",
    description: "Treine 5 dias nesta semana.",
    type: "frequency",
    category: "weekly",
    difficulty: "hard",
    goal: 5,
    durationDays: 7,
    rewardXp: calculateChallengeXP("hard", 7),
    icon: "Calendar",
  },
  {
    id: "c4",
    title: "Desafio da Comunidade: 10k",
    description: "Corra 10km acumulados.",
    type: "volume",
    category: "community",
    difficulty: "epic",
    goal: 10,
    durationDays: 14,
    rewardXp: calculateChallengeXP("epic", 14),
    icon: "Trophy",
    communityId: "mock-community-1",
  },
];

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [];

export const ACHIEVEMENTS: Achievement[] = [
  // Athlete Achievements
  {
    id: "a1",
    name: "Primeiro treino",
    description: "Complete seu primeiro treino.",
    category: "Consistency",
    criteria: "1 treino",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Dumbbell",
    xpValue: 100,
  },
  {
    id: "a2",
    name: "Streak 7 dias",
    description: "Treine por 7 dias seguidos.",
    category: "Consistency",
    criteria: "7 dias",
    progress: 3,
    maxProgress: 7,
    icon: "Flame",
    xpValue: 500,
  },
  {
    id: "a3",
    name: "PR no supino",
    description: "Bata seu recorde pessoal no Supino.",
    category: "Strength",
    criteria: "Novo recorde",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Trophy",
    xpValue: 250,
  },
  {
    id: "a4",
    name: "Volume 100k kg",
    description: "Acumule 100.000 kg de volume total.",
    category: "Volume",
    criteria: "100.000 kg",
    progress: 45000,
    maxProgress: 100000,
    icon: "Weight",
    xpValue: 1000,
  },
  {
    id: "a5",
    name: "Atleta focado",
    description: "Complete 10 treinos no total.",
    category: "Consistency",
    criteria: "10 treinos",
    progress: 4,
    maxProgress: 10,
    icon: "Target",
    xpValue: 800,
  },
  {
    id: "a6",
    name: "Madrugador",
    description: "Treine 5 vezes antes das 8h da manhã.",
    category: "Frequency",
    criteria: "5 treinos",
    progress: 2,
    maxProgress: 5,
    icon: "Sun",
    xpValue: 600,
  },

  // Trainer Achievements
  {
    id: "t1",
    name: "Primeiro aluno",
    description: "Conecte-se com seu primeiro aluno.",
    category: "Engagement",
    criteria: "1 aluno",
    progress: 1,
    maxProgress: 1,
    icon: "Users",
    xpValue: 200,
  },
  {
    id: "t2",
    name: "Mestre dos treinos",
    description: "Crie 10 templates de treino.",
    category: "Mentorship",
    criteria: "10 templates",
    progress: 4,
    maxProgress: 10,
    icon: "FileText",
    xpValue: 500,
  },
  {
    id: "t3",
    name: "Treinador popular",
    description: "Tenha 10 alunos ativos simultaneamente.",
    category: "Community",
    criteria: "10 alunos",
    progress: 3,
    maxProgress: 10,
    icon: "Star",
    xpValue: 1000,
  },
  {
    id: "t4",
    name: "Feedback constante",
    description: "Envie 20 mensagens para seus alunos.",
    category: "Engagement",
    criteria: "20 mensagens",
    progress: 12,
    maxProgress: 20,
    icon: "MessageSquare",
    xpValue: 400,
  },
  {
    id: "t5",
    name: "Alunos focados",
    description: "Seus alunos completaram 50 treinos no total.",
    category: "Mentorship",
    criteria: "50 treinos",
    progress: 23,
    maxProgress: 50,
    icon: "Award",
    xpValue: 1500,
  },
  {
    id: "t6",
    name: "Treinador de elite",
    description: "5 alunos atingiram streak de 7 dias.",
    category: "Mentorship",
    criteria: "5 alunos",
    progress: 1,
    maxProgress: 5,
    icon: "Crown",
    xpValue: 2000,
  },
  
  // Challenge Achievements
  {
    id: "c1",
    name: "Desafiante iniciante",
    description: "Complete seu primeiro desafio.",
    category: "Challenges",
    criteria: "1 desafio",
    progress: 1,
    maxProgress: 1,
    unlockedAt: undefined,
    icon: "Swords",
    xpValue: 150,
  },
  {
    id: "c2",
    name: "Competidor nato",
    description: "Complete 10 desafios no total.",
    category: "Challenges",
    criteria: "10 desafios",
    progress: 3,
    maxProgress: 10,
    icon: "Medal",
    xpValue: 600,
  },
  {
    id: "c3",
    name: "Rei do cardio",
    description: "Complete 5 desafios da categoria Cardio.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 2,
    maxProgress: 5,
    icon: "Activity",
    xpValue: 400,
  },
  {
    id: "c4",
    name: "Força bruta",
    description: "Complete 5 desafios da categoria Força.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 1,
    maxProgress: 5,
    icon: "Dumbbell",
    xpValue: 400,
  },
  {
    id: "c5",
    name: "Consistência de ferro",
    description: "Complete 5 desafios da categoria Consistência.",
    category: "Challenges",
    criteria: "5 desafios",
    progress: 4,
    maxProgress: 5,
    icon: "Flame",
    xpValue: 400,
  }
];

export const MOCK_PROTOCOLS = [];

export const DEFAULT_STATS: UserStats = {
  level: 1,
  xp: 0,
  streak: 0,
  bestStreak: 0,
  weeklyGoal: 3,
  completedThisWeek: 0,
  totalWorkouts: 0,
  totalVolume: 0,
  medalsCount: 0,
  league: "Bronze",
};

export const DEFAULT_TRAINING_PROFILE: UserTrainingProfile = {
  user_id: "",
  avg_set_duration: 45,
  avg_rest_duration: 90,
  avg_transition_duration: 120,
  avg_workout_duration: 3600,
};

export const DEFAULT_PROFILE: UserProfile = {
  name: "",
  email: "",
  height: 0,
  initialWeight: 0,
  objective: "",
  birthDate: "",
  avatarUrl:
    "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=2070&auto=format&fit=crop",
  userType: "atleta",
};
